#!/usr/bin/env python3
"""Generate model-specific TOML configuration files for Abliterix.

Usage:
    python scripts/generate_configs.py              # Generate all missing configs
    python scripts/generate_configs.py --overwrite   # Regenerate all configs
    python scripts/generate_configs.py --family llama # Only generate Llama configs
    python scripts/generate_configs.py --dry-run     # Preview without writing
"""

import argparse
import os
from dataclasses import dataclass

CONFIGS_DIR = os.path.join(os.path.dirname(__file__), "..", "configs")


@dataclass
class ModelSpec:
    slug: str              # Filename stem, e.g. "llama3.1_8b"
    model_id: str          # HuggingFace model ID
    family: str            # For filtering: "llama", "gemma", "phi", etc.
    size_b: float          # Total parameter count in billions
    arch: str              # "dense", "moe", "ssm", "vlm"
    comment: str           # Architecture description for file header
    quant: str = "none"    # "none", "bnb_4bit", "bnb_8bit", "fp8"
    trust_remote_code: bool = False
    active_b: float | None = None  # Active params for MoE


# ---------------------------------------------------------------------------
# Tier-based defaults
# ---------------------------------------------------------------------------

def _tier_defaults(size_b: float, arch: str, quant: str) -> dict:
    """Compute sensible defaults based on model size and architecture."""
    # Effective size for memory estimation
    effective = size_b
    if quant == "bnb_4bit":
        effective = size_b * 0.3
    elif quant in ("bnb_8bit", "fp8"):
        effective = size_b * 0.55

    if effective < 3:
        tier = dict(max_batch_size=64, num_trials=50, num_warmup=15, kl_tokens=1)
    elif effective < 10:
        tier = dict(max_batch_size=32, num_trials=50, num_warmup=15, kl_tokens=1)
    elif effective < 30:
        tier = dict(max_batch_size=8, num_trials=50, num_warmup=15, kl_tokens=1)
    elif effective < 80:
        tier = dict(max_batch_size=4, num_trials=50, num_warmup=15, kl_tokens=3)
    else:
        tier = dict(max_batch_size=4, num_trials=25, num_warmup=10, kl_tokens=3)

    # MoE models need wider strength range
    if arch == "moe":
        tier["strength_lo"] = 1.0
        tier["strength_hi"] = 10.0
    else:
        tier["strength_lo"] = 0.8
        tier["strength_hi"] = 1.5

    # Memory map estimation (BF16 bytes)
    bf16_gb = size_b * 2
    if quant == "bnb_4bit":
        bf16_gb = size_b * 0.6
    elif quant in ("bnb_8bit", "fp8"):
        bf16_gb = size_b * 1.1

    # Compute GPU allocation
    per_gpu = 78  # GiB per H100/A100
    n_gpus = max(1, int(bf16_gb / per_gpu) + 1)
    if n_gpus == 1:
        tier["max_memory"] = None
    else:
        mem_entries = ", ".join(f'{i} = "{per_gpu}GiB"' for i in range(n_gpus))
        tier["max_memory"] = f"{{{mem_entries}}}"

    # Dtype
    if quant != "none":
        tier["dtype"] = '["auto"]'
    else:
        tier["dtype"] = '["bfloat16"]'

    return tier


def _render_toml(spec: ModelSpec) -> str:
    """Render a model-specific TOML configuration string."""
    t = _tier_defaults(spec.size_b, spec.arch, spec.quant)

    quant_suffix = ""
    if spec.quant == "bnb_4bit":
        quant_suffix = ", 4-bit quantized"
    elif spec.quant == "fp8":
        quant_suffix = ", FP8 quantized"
    elif spec.quant == "bnb_8bit":
        quant_suffix = ", 8-bit quantized"

    lines = [
        f"# {spec.comment}{quant_suffix}",
        f"# Generated by scripts/generate_configs.py",
        "",
        "[model]",
        f'model_id = "{spec.model_id}"',
        f"dtype_fallback_order = {t['dtype']}",
        f'quant_method = "{spec.quant}"',
        "use_torch_compile = false",
        'device_map = "auto"',
    ]

    if spec.trust_remote_code:
        lines.append("trust_remote_code = true")

    if t["max_memory"]:
        lines.append(f"max_memory = {t['max_memory']}")

    lines += [
        "",
        "[inference]",
        "batch_size = 0",
        f"max_batch_size = {t['max_batch_size']}",
        "max_gen_tokens = 50",
        "",
        "[steering]",
        'vector_method = "mean"',
        'decay_kernel = "linear"',
        "orthogonal_projection = true",
        f"strength_range = [{t['strength_lo']}, {t['strength_hi']}]",
        "",
        "[optimization]",
        f"num_trials = {t['num_trials']}",
        f"num_warmup_trials = {t['num_warmup']}",
        f'checkpoint_dir = "checkpoints_{spec.slug}"',
        "",
        "[kl]",
        "scale = 1.0",
        f"token_count = {t['kl_tokens']}",
        "target = 0.01",
        "prune_threshold = 5.0",
        "",
        "[display]",
        "print_responses = false",
    ]

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Model specifications
# ---------------------------------------------------------------------------

MODELS: list[ModelSpec] = [
    # --- Llama family ---
    ModelSpec("llama3.1_8b", "meta-llama/Llama-3.1-8B-Instruct", "llama", 8, "dense",
             "Llama 3.1 8B Instruct (dense, 32 layers, hidden=4096)"),
    ModelSpec("llama3.1_70b", "meta-llama/Llama-3.1-70B-Instruct", "llama", 70, "dense",
             "Llama 3.1 70B Instruct (dense, 80 layers, hidden=8192)"),
    ModelSpec("llama3.1_70b_4bit", "meta-llama/Llama-3.1-70B-Instruct", "llama", 70, "dense",
             "Llama 3.1 70B Instruct", quant="bnb_4bit"),
    ModelSpec("llama3.1_405b_4bit", "meta-llama/Llama-3.1-405B-Instruct", "llama", 405, "dense",
             "Llama 3.1 405B Instruct", quant="bnb_4bit"),
    ModelSpec("llama3.2_1b", "meta-llama/Llama-3.2-1B-Instruct", "llama", 1, "dense",
             "Llama 3.2 1B Instruct (dense, 16 layers, hidden=2048)"),
    ModelSpec("llama3.2_3b", "meta-llama/Llama-3.2-3B-Instruct", "llama", 3, "dense",
             "Llama 3.2 3B Instruct (dense, 28 layers, hidden=3072)"),
    ModelSpec("llama3.2_11b_vision", "meta-llama/Llama-3.2-11B-Vision-Instruct", "llama", 11, "vlm",
             "Llama 3.2 11B Vision Instruct (VLM)"),
    ModelSpec("llama3.2_90b_vision_4bit", "meta-llama/Llama-3.2-90B-Vision-Instruct", "llama", 90, "vlm",
             "Llama 3.2 90B Vision Instruct (VLM)", quant="bnb_4bit"),
    ModelSpec("llama3.3_70b", "meta-llama/Llama-3.3-70B-Instruct", "llama", 70, "dense",
             "Llama 3.3 70B Instruct (dense, 80 layers, hidden=8192)"),
    ModelSpec("llama3.3_70b_4bit", "meta-llama/Llama-3.3-70B-Instruct", "llama", 70, "dense",
             "Llama 3.3 70B Instruct", quant="bnb_4bit"),
    ModelSpec("llama4_scout_109b", "meta-llama/Llama-4-Scout-17B-16E-Instruct", "llama", 109, "moe",
             "Llama 4 Scout 109B MoE (17B active, 16 experts)", active_b=17),
    ModelSpec("llama4_maverick_401b_4bit", "meta-llama/Llama-4-Maverick-17B-128E-Instruct", "llama", 401, "moe",
             "Llama 4 Maverick 401B MoE (17B active, 128 experts)", quant="bnb_4bit", active_b=17),
    ModelSpec("llama3.1_8b_fp8", "meta-llama/Llama-3.1-8B-Instruct", "llama", 8, "dense",
             "Llama 3.1 8B Instruct", quant="fp8"),
    ModelSpec("llama3.1_70b_fp8", "meta-llama/Llama-3.1-70B-Instruct", "llama", 70, "dense",
             "Llama 3.1 70B Instruct", quant="fp8"),
    ModelSpec("llama_guard_4_12b", "meta-llama/Llama-Guard-4-12B", "llama", 12, "dense",
             "Llama Guard 4 12B (safety classifier, dense)"),
    ModelSpec("llama3.1_nemotron_70b_4bit", "nvidia/Llama-3.1-Nemotron-70B-Instruct-HF", "llama", 70, "dense",
             "Llama 3.1 Nemotron 70B Instruct", quant="bnb_4bit"),

    # --- Gemma family ---
    ModelSpec("gemma2_2b", "google/gemma-2-2b-it", "gemma", 2, "dense",
             "Gemma 2 2B Instruct (dense, 18 layers, hidden=2304)"),
    ModelSpec("gemma2_9b", "google/gemma-2-9b-it", "gemma", 9, "dense",
             "Gemma 2 9B Instruct (dense, 42 layers, hidden=3584)"),
    ModelSpec("gemma2_27b", "google/gemma-2-27b-it", "gemma", 27, "dense",
             "Gemma 2 27B Instruct (dense, 46 layers, hidden=4608)"),
    ModelSpec("gemma3_1b", "google/gemma-3-1b-it", "gemma", 1, "dense",
             "Gemma 3 1B Instruct (dense)"),
    ModelSpec("gemma3_4b", "google/gemma-3-4b-it", "gemma", 4, "dense",
             "Gemma 3 4B Instruct (dense)"),
    ModelSpec("gemma3_12b", "google/gemma-3-12b-it", "gemma", 12, "dense",
             "Gemma 3 12B Instruct (dense)"),
    ModelSpec("gemma3_27b", "google/gemma-3-27b-it", "gemma", 27, "dense",
             "Gemma 3 27B Instruct (dense)"),
    ModelSpec("gemma3_27b_4bit", "google/gemma-3-27b-it", "gemma", 27, "dense",
             "Gemma 3 27B Instruct", quant="bnb_4bit"),

    # --- Phi family ---
    ModelSpec("phi3_mini_4k", "microsoft/Phi-3-mini-4k-instruct", "phi", 3.8, "dense",
             "Phi-3 Mini 4K Instruct (dense, 32 layers, hidden=3072)"),
    ModelSpec("phi3_small_8k", "microsoft/Phi-3-small-8k-instruct", "phi", 7, "dense",
             "Phi-3 Small 8K Instruct (dense, 32 layers, hidden=4096)", trust_remote_code=True),
    ModelSpec("phi3_medium_4k", "microsoft/Phi-3-medium-4k-instruct", "phi", 14, "dense",
             "Phi-3 Medium 4K Instruct (dense, 40 layers, hidden=5120)"),
    ModelSpec("phi3.5_mini", "microsoft/Phi-3.5-mini-instruct", "phi", 3.8, "dense",
             "Phi-3.5 Mini Instruct (dense)"),
    ModelSpec("phi3.5_moe", "microsoft/Phi-3.5-MoE-instruct", "phi", 42, "moe",
             "Phi-3.5 MoE Instruct (42B total, 16 experts, top-2)", active_b=6.6),
    ModelSpec("phi4_mini", "microsoft/phi-4-mini-instruct", "phi", 3.8, "dense",
             "Phi-4 Mini Instruct (dense)"),
    ModelSpec("phi4", "microsoft/phi-4", "phi", 14, "dense",
             "Phi-4 14B (dense, 40 layers, hidden=5120)"),
    ModelSpec("phi4_reasoning", "microsoft/Phi-4-reasoning", "phi", 14, "dense",
             "Phi-4 Reasoning (CoT, dense)"),
    ModelSpec("phi4_mini_reasoning", "microsoft/Phi-4-mini-reasoning", "phi", 3.8, "dense",
             "Phi-4 Mini Reasoning (CoT, dense)"),

    # --- DeepSeek family ---
    ModelSpec("deepseek_v2_lite", "deepseek-ai/DeepSeek-V2-Lite-Chat", "deepseek", 16, "moe",
             "DeepSeek V2 Lite Chat (16B MoE)", trust_remote_code=True),
    ModelSpec("deepseek_v2.5_4bit", "deepseek-ai/DeepSeek-V2.5", "deepseek", 236, "moe",
             "DeepSeek V2.5 (236B MoE)", quant="bnb_4bit", trust_remote_code=True),
    ModelSpec("deepseek_r1_distill_7b", "deepseek-ai/DeepSeek-R1-Distill-Llama-7B", "deepseek", 7, "dense",
             "DeepSeek R1 Distill Llama 7B (dense, CoT)"),
    ModelSpec("deepseek_r1_distill_14b", "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B", "deepseek", 14, "dense",
             "DeepSeek R1 Distill Qwen 14B (dense, CoT)"),
    ModelSpec("deepseek_r1_distill_32b", "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B", "deepseek", 32, "dense",
             "DeepSeek R1 Distill Qwen 32B (dense, CoT)"),
    ModelSpec("deepseek_r1_distill_32b_4bit", "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B", "deepseek", 32, "dense",
             "DeepSeek R1 Distill Qwen 32B", quant="bnb_4bit"),

    # --- Yi family ---
    ModelSpec("yi1.5_6b", "01-ai/Yi-1.5-6B-Chat", "yi", 6, "dense",
             "Yi 1.5 6B Chat (dense)"),
    ModelSpec("yi1.5_9b", "01-ai/Yi-1.5-9B-Chat", "yi", 9, "dense",
             "Yi 1.5 9B Chat (dense)"),
    ModelSpec("yi1.5_34b", "01-ai/Yi-1.5-34B-Chat", "yi", 34, "dense",
             "Yi 1.5 34B Chat (dense, 60 layers, hidden=7168)"),
    ModelSpec("yi_coder_9b", "01-ai/Yi-Coder-9B-Chat", "yi", 9, "dense",
             "Yi Coder 9B Chat (code, dense)"),

    # --- InternLM family ---
    ModelSpec("internlm2.5_7b", "internlm/internlm2_5-7b-chat", "internlm", 7, "dense",
             "InternLM 2.5 7B Chat (dense)", trust_remote_code=True),
    ModelSpec("internlm2.5_20b", "internlm/internlm2_5-20b-chat", "internlm", 20, "dense",
             "InternLM 2.5 20B Chat (dense)", trust_remote_code=True),
    ModelSpec("internlm3_8b", "internlm/internlm3-8b-instruct", "internlm", 8, "dense",
             "InternLM 3 8B Instruct (dense)", trust_remote_code=True),

    # --- Mistral family (extending existing) ---
    ModelSpec("mistral_7b_v0.3", "mistralai/Mistral-7B-Instruct-v0.3", "mistral", 7, "dense",
             "Mistral 7B Instruct v0.3 (dense, 32 layers, hidden=4096)"),
    ModelSpec("mistral_nemo_12b", "mistralai/Mistral-Nemo-Instruct-2407", "mistral", 12, "dense",
             "Mistral Nemo 12B Instruct (dense, 40 layers, hidden=5120)"),
    ModelSpec("mistral_small_24b", "mistralai/Mistral-Small-Instruct-2409", "mistral", 24, "dense",
             "Mistral Small 24B Instruct (dense)"),
    ModelSpec("mistral_large_123b_4bit", "mistralai/Mistral-Large-Instruct-2411", "mistral", 123, "dense",
             "Mistral Large 123B Instruct", quant="bnb_4bit"),
    ModelSpec("mixtral_8x7b", "mistralai/Mixtral-8x7B-Instruct-v0.1", "mistral", 47, "moe",
             "Mixtral 8x7B Instruct (MoE, 8 experts, top-2)", active_b=13),
    ModelSpec("mixtral_8x22b_4bit", "mistralai/Mixtral-8x22B-Instruct-v0.1", "mistral", 141, "moe",
             "Mixtral 8x22B Instruct (MoE)", quant="bnb_4bit", active_b=39),
    ModelSpec("codestral_22b", "mistralai/Codestral-22B-v0.1", "mistral", 22, "dense",
             "Codestral 22B (code, dense)"),
    ModelSpec("mistral_small3_24b", "mistralai/Mistral-Small-3.1-24B-Instruct-2503", "mistral", 24, "dense",
             "Mistral Small 3.1 24B Instruct (dense)"),

    # --- Cohere Command-R family ---
    ModelSpec("command_r_35b", "CohereForAI/c4ai-command-r-v01", "cohere", 35, "dense",
             "Command-R 35B (dense)"),
    ModelSpec("command_r_plus_104b_4bit", "CohereForAI/c4ai-command-r-plus", "cohere", 104, "dense",
             "Command-R+ 104B", quant="bnb_4bit"),
    ModelSpec("aya_expanse_32b", "CohereForAI/aya-expanse-32b", "cohere", 32, "dense",
             "Aya Expanse 32B (multilingual, dense)"),

    # --- Falcon family ---
    ModelSpec("falcon2_11b", "tiiuae/falcon-11B", "falcon", 11, "dense",
             "Falcon 2 11B (dense)"),
    ModelSpec("falcon3_1b", "tiiuae/Falcon3-1B-Instruct", "falcon", 1, "dense",
             "Falcon 3 1B Instruct (dense)"),
    ModelSpec("falcon3_7b", "tiiuae/Falcon3-7B-Instruct", "falcon", 7, "dense",
             "Falcon 3 7B Instruct (dense)"),
    ModelSpec("falcon3_10b", "tiiuae/Falcon3-10B-Instruct", "falcon", 10, "dense",
             "Falcon 3 10B Instruct (dense)"),

    # --- StarCoder2 + Code models ---
    ModelSpec("starcoder2_3b", "bigcode/starcoder2-3b", "code", 3, "dense",
             "StarCoder2 3B (code, dense)"),
    ModelSpec("starcoder2_7b", "bigcode/starcoder2-7b", "code", 7, "dense",
             "StarCoder2 7B (code, dense)"),
    ModelSpec("starcoder2_15b", "bigcode/starcoder2-15b", "code", 15, "dense",
             "StarCoder2 15B (code, dense)"),
    ModelSpec("qwen2.5_coder_7b", "Qwen/Qwen2.5-Coder-7B-Instruct", "code", 7, "dense",
             "Qwen 2.5 Coder 7B Instruct (code, dense)"),

    # --- Qwen 2/2.5 family ---
    ModelSpec("qwen2_0.5b", "Qwen/Qwen2-0.5B-Instruct", "qwen", 0.5, "dense",
             "Qwen 2 0.5B Instruct (dense)"),
    ModelSpec("qwen2_1.5b", "Qwen/Qwen2-1.5B-Instruct", "qwen", 1.5, "dense",
             "Qwen 2 1.5B Instruct (dense)"),
    ModelSpec("qwen2_7b", "Qwen/Qwen2-7B-Instruct", "qwen", 7, "dense",
             "Qwen 2 7B Instruct (dense, 28 layers, hidden=3584)"),
    ModelSpec("qwen2_72b_4bit", "Qwen/Qwen2-72B-Instruct", "qwen", 72, "dense",
             "Qwen 2 72B Instruct", quant="bnb_4bit"),
    ModelSpec("qwen2.5_0.5b", "Qwen/Qwen2.5-0.5B-Instruct", "qwen", 0.5, "dense",
             "Qwen 2.5 0.5B Instruct (dense)"),
    ModelSpec("qwen2.5_1.5b", "Qwen/Qwen2.5-1.5B-Instruct", "qwen", 1.5, "dense",
             "Qwen 2.5 1.5B Instruct (dense)"),
    ModelSpec("qwen2.5_3b", "Qwen/Qwen2.5-3B-Instruct", "qwen", 3, "dense",
             "Qwen 2.5 3B Instruct (dense)"),
    ModelSpec("qwen2.5_7b", "Qwen/Qwen2.5-7B-Instruct", "qwen", 7, "dense",
             "Qwen 2.5 7B Instruct (dense, 28 layers, hidden=3584)"),
    ModelSpec("qwen2.5_14b", "Qwen/Qwen2.5-14B-Instruct", "qwen", 14, "dense",
             "Qwen 2.5 14B Instruct (dense, 48 layers, hidden=5120)"),
    ModelSpec("qwen2.5_32b", "Qwen/Qwen2.5-32B-Instruct", "qwen", 32, "dense",
             "Qwen 2.5 32B Instruct (dense, 64 layers, hidden=5120)"),
    ModelSpec("qwen2.5_72b_4bit", "Qwen/Qwen2.5-72B-Instruct", "qwen", 72, "dense",
             "Qwen 2.5 72B Instruct", quant="bnb_4bit"),
    ModelSpec("qwen2.5_72b_fp8", "Qwen/Qwen2.5-72B-Instruct", "qwen", 72, "dense",
             "Qwen 2.5 72B Instruct", quant="fp8"),

    # --- SmolLM / OLMo / MAP-Neo ---
    ModelSpec("smollm2_135m", "HuggingFaceTB/SmolLM2-135M-Instruct", "smollm", 0.135, "dense",
             "SmolLM2 135M Instruct (dense, tiny)"),
    ModelSpec("smollm2_360m", "HuggingFaceTB/SmolLM2-360M-Instruct", "smollm", 0.36, "dense",
             "SmolLM2 360M Instruct (dense, tiny)"),
    ModelSpec("smollm2_1.7b", "HuggingFaceTB/SmolLM2-1.7B-Instruct", "smollm", 1.7, "dense",
             "SmolLM2 1.7B Instruct (dense)"),
    ModelSpec("olmo2_7b", "allenai/OLMo-2-1124-7B-Instruct", "olmo", 7, "dense",
             "OLMo 2 7B Instruct (dense)"),
    ModelSpec("olmo2_13b", "allenai/OLMo-2-1124-13B-Instruct", "olmo", 13, "dense",
             "OLMo 2 13B Instruct (dense)"),
    ModelSpec("map_neo_7b", "m-a-p/neo_7b_instruct_v0.1", "other", 7, "dense",
             "MAP-Neo 7B Instruct (dense)"),

    # --- Chinese models ---
    ModelSpec("chatglm3_6b", "THUDM/chatglm3-6b", "chinese", 6, "dense",
             "ChatGLM3 6B (dense, GLM architecture)", trust_remote_code=True),
    ModelSpec("glm4_9b", "THUDM/glm-4-9b-chat", "chinese", 9, "dense",
             "GLM-4 9B Chat (dense)", trust_remote_code=True),
    ModelSpec("baichuan2_7b", "baichuan-inc/Baichuan2-7B-Chat", "chinese", 7, "dense",
             "Baichuan2 7B Chat (dense)", trust_remote_code=True),
    ModelSpec("baichuan2_13b", "baichuan-inc/Baichuan2-13B-Chat", "chinese", 13, "dense",
             "Baichuan2 13B Chat (dense)", trust_remote_code=True),
    ModelSpec("minicpm_2b", "openbmb/MiniCPM-2B-sft-bf16", "chinese", 2, "dense",
             "MiniCPM 2B (dense)"),
    ModelSpec("minicpm3_4b", "openbmb/MiniCPM3-4B", "chinese", 4, "dense",
             "MiniCPM3 4B (dense)", trust_remote_code=True),
    ModelSpec("yuan2_2b", "IEITYuan/Yuan2-2B-hf", "chinese", 2, "dense",
             "Yuan2 2B (dense)"),
    ModelSpec("xverse_13b", "xverse/XVERSE-13B-Chat", "chinese", 13, "dense",
             "XVERSE 13B Chat (dense)", trust_remote_code=True),

    # --- Other notable models ---
    ModelSpec("solar_10.7b", "upstage/SOLAR-10.7B-Instruct-v1.0", "other", 10.7, "dense",
             "SOLAR 10.7B Instruct (dense, depth-upscaled)"),
    ModelSpec("exaone3.5_2.4b", "LGAI-EXAONE/EXAONE-3.5-2.4B-Instruct", "exaone", 2.4, "dense",
             "EXAONE 3.5 2.4B Instruct (dense)", trust_remote_code=True),
    ModelSpec("exaone3.5_7.8b", "LGAI-EXAONE/EXAONE-3.5-7.8B-Instruct", "exaone", 7.8, "dense",
             "EXAONE 3.5 7.8B Instruct (dense)", trust_remote_code=True),
    ModelSpec("exaone3.5_32b", "LGAI-EXAONE/EXAONE-3.5-32B-Instruct", "exaone", 32, "dense",
             "EXAONE 3.5 32B Instruct (dense)", trust_remote_code=True),
    ModelSpec("granite3.1_8b", "ibm-granite/granite-3.1-8b-instruct", "granite", 8, "dense",
             "Granite 3.1 8B Instruct (dense)"),
    ModelSpec("granite3.1_3b_moe", "ibm-granite/granite-3.1-3b-a800m-instruct", "granite", 3, "moe",
             "Granite 3.1 3B MoE (800M active)", active_b=0.8),
    ModelSpec("jamba1.5_mini", "ai21labs/AI21-Jamba-1.5-Mini", "jamba", 12, "ssm",
             "Jamba 1.5 Mini 12B (SSM+MoE hybrid, Mamba+attention)", trust_remote_code=True),
    ModelSpec("jamba1.5_large_4bit", "ai21labs/AI21-Jamba-1.5-Large", "jamba", 94, "ssm",
             "Jamba 1.5 Large 94B (SSM+MoE hybrid)", quant="bnb_4bit", trust_remote_code=True),
    ModelSpec("dbrx_132b_4bit", "databricks/dbrx-instruct", "other", 132, "moe",
             "DBRX 132B Instruct (MoE)", quant="bnb_4bit", trust_remote_code=True),
    ModelSpec("zephyr_7b", "HuggingFaceH4/zephyr-7b-beta", "other", 7, "dense",
             "Zephyr 7B Beta (dense, Mistral-based)"),
    ModelSpec("openchat_3.5", "openchat/openchat-3.5-0106", "other", 7, "dense",
             "OpenChat 3.5 (dense, Mistral-based)"),

    # --- VLM models ---
    ModelSpec("qwen2_vl_7b", "Qwen/Qwen2-VL-7B-Instruct", "vlm", 7, "vlm",
             "Qwen2 VL 7B Instruct (Vision-Language)"),
    ModelSpec("internvl2_8b", "OpenGVLab/InternVL2-8B", "vlm", 8, "vlm",
             "InternVL2 8B (Vision-Language)", trust_remote_code=True),
    ModelSpec("llava_next_34b_4bit", "llava-hf/llava-v1.6-34b-hf", "vlm", 34, "vlm",
             "LLaVA-NeXT 34B (Vision-Language)", quant="bnb_4bit"),
    ModelSpec("pixtral_12b", "mistralai/Pixtral-12B-2409", "vlm", 12, "vlm",
             "Pixtral 12B (Vision-Language, Mistral-based)"),

    # --- Additional quantization variants ---
    ModelSpec("mistral_nemo_12b_fp8", "mistralai/Mistral-Nemo-Instruct-2407", "mistral", 12, "dense",
             "Mistral Nemo 12B Instruct", quant="fp8"),
    ModelSpec("phi4_fp8", "microsoft/phi-4", "phi", 14, "dense",
             "Phi-4 14B", quant="fp8"),
    ModelSpec("deepseek_r1_distill_14b_4bit", "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B", "deepseek", 14, "dense",
             "DeepSeek R1 Distill Qwen 14B", quant="bnb_4bit"),
    ModelSpec("gemma2_9b_fp8", "google/gemma-2-9b-it", "gemma", 9, "dense",
             "Gemma 2 9B Instruct", quant="fp8"),
]


def main():
    parser = argparse.ArgumentParser(description="Generate Abliterix model configs")
    parser.add_argument("--overwrite", action="store_true", help="Overwrite existing configs")
    parser.add_argument("--dry-run", action="store_true", help="Preview without writing")
    parser.add_argument("--family", type=str, help="Only generate for this model family")
    args = parser.parse_args()

    os.makedirs(CONFIGS_DIR, exist_ok=True)

    generated = 0
    skipped = 0

    for spec in MODELS:
        if args.family and spec.family != args.family:
            continue

        path = os.path.join(CONFIGS_DIR, f"{spec.slug}.toml")

        if os.path.exists(path) and not args.overwrite:
            skipped += 1
            continue

        content = _render_toml(spec)

        if args.dry_run:
            print(f"[DRY RUN] Would write: {path}")
        else:
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"Generated: {path}")

        generated += 1

    print(f"\nDone: {generated} generated, {skipped} skipped (already exist)")
    print(f"Total configs in directory: {len([f for f in os.listdir(CONFIGS_DIR) if f.endswith('.toml')])}")


if __name__ == "__main__":
    main()
